### ISSUE TITLE
Using MultiGPU Faster-RCNN

### ISSUE THREAD

**Issue by superx21** [bharatsingh430/py-R-FCN-multiGPU#1]
Hi, thx for the code sharing. 
I am interested in running Faster RCNN with multi-GPU only (without FCN modification). 
As I understand, I only need to set AGNOSTIC as False, and then all the things are the same as the original F-RCNN code, right?

**Comment by bharatsingh430** [comment]
Yes, it should work. I have added a training script for faster-rcnn using VGG. If you need to use more gpus, you can specify them in the faster_rcnn_end2end_multi_gpu.sh file. Note that batch size of also changes when you add more GPUs.

**Comment by 315386775** [comment]
@superx21  set AGNOSTIC as False? where is it?
