### ISSUE TITLE
The detection results

### ISSUE THREAD

**Issue by taokong** [bharatsingh430/py-R-FCN-multiGPU#2]
Hi, Bharat.
Glad to hear the multi-gpus version of faster R-CNN. Can you provide the testing detection mAP on psacal voc dataset? or COCO dataset? I'm curious if the the version is better than /comparable with the single-gpu version.

**Comment by crazylyf** [comment]
taokong,
I have just compared the original single-GPU version and multi-GPU version, and found out that multi-GPU version is comparable with original results. The experiment is done on my own dataset, and the faster R-CNN architecture is also modified. Despite of that, I think the conclusion should remain.

**Comment by taokong** [comment]
@crazylyf thank you very much for response.
