### ISSUE TITLE
pretrained model on mscoco

### ISSUE THREAD

**Issue by funnyzhou** [bharatsingh430/py-R-FCN-multiGPU#4]
I'm very happy to see a released R-FCN model on MS COCO. However, I noticed that the coco test_agnostic.prototxt didn't fit the released model well. Would you please release the right prototxt?

**Comment by bharatsingh430** [comment]
did you use the coco branch? What error do you get?

**Comment by funnyzhou** [comment]
For example, the output dimenson of "rpn_cls_score" in the released model is 30, while in the test_agnostic.prototxt, it is 24. Is this my fault?

**Comment by bharatsingh430** [comment]
you need to clone the coco branch, not master

**Comment by funnyzhou** [comment]
Ok :). I got it. Thank you very much.
