### ISSUE TITLE
do you make this caffe by yourself?

### ISSUE THREAD

**Issue by KeyKy** [bharatsingh430/py-R-FCN-multiGPU#7]
I find the caffe you use can support python layer multi-gpus training. Do you make the caffe by yourself or fork from somewhere?

**Comment by bharatsingh430** [comment]
I merged the current caffe branch and r-fcn caffe branch. batch normalization in current caffe take more memory. Also, layers specific to detection are not present, so they were added. Python layers were added for multi-gpu training.

**Comment by KeyKy** [comment]
@bharatsingh430 why does it detect so slow in test phase by using your caffe (but i use my implementation of faster-rcnn, VGG16 net_forward: 0.467s/img). It should be 0.080s/img.

**Comment by KeyKy** [comment]
@bharatsingh430 could your show me how you reduce batch normalization memory? Where is changes?

**Comment by bharatsingh430** [comment]
I used batch normalization from py-r-fcn instead of the main caffe branch.
